server:
  port: 3000

spring:
  application:
    name: onepiecetcg-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/onepiecetcg
    username: ${DB_USERNAME:onepiecetcg}
    password: ${DB_PASSWORD:onepiecetcg}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

sets:
  sync:
    cron: "0 0 3 * * *"

set-cards:
  sync:
    cron: "0 15 3 * * *"

promo-cards:
  sync:
    cron: "0 30 3 * * *"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    pl.janda.onepiecetcg: DEBUG
    org.springframework.web: INFO
