/*
 * This file is generated by jOOQ.
 */
package pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.CardSets;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CardSetsRecord extends UpdatableRecordImpl<CardSetsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.card_sets.set_id</code>.
     */
    public void setSetId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.card_sets.set_id</code>.
     */
    public String getSetId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.card_sets.last_synced_at</code>.
     */
    public void setLastSyncedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.card_sets.last_synced_at</code>.
     */
    public LocalDateTime getLastSyncedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.card_sets.set_name</code>.
     */
    public void setSetName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.card_sets.set_name</code>.
     */
    public String getSetName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CardSetsRecord
     */
    public CardSetsRecord() {
        super(CardSets.CARD_SETS);
    }

    /**
     * Create a detached, initialised CardSetsRecord
     */
    public CardSetsRecord(String setId, LocalDateTime lastSyncedAt, String setName) {
        super(CardSets.CARD_SETS);

        setSetId(setId);
        setLastSyncedAt(lastSyncedAt);
        setSetName(setName);
        resetTouchedOnNotNull();
    }
}
