/*
 * This file is generated by jOOQ.
 */
package pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.CardFilterOptions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CardFilterOptionsRecord extends UpdatableRecordImpl<CardFilterOptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.card_filter_options.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.card_filter_options.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.card_filter_options.category</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.card_filter_options.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.card_filter_options.label</code>.
     */
    public void setLabel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.card_filter_options.label</code>.
     */
    public String getLabel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.card_filter_options.value</code>.
     */
    public void setValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.card_filter_options.value</code>.
     */
    public String getValue() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CardFilterOptionsRecord
     */
    public CardFilterOptionsRecord() {
        super(CardFilterOptions.CARD_FILTER_OPTIONS);
    }

    /**
     * Create a detached, initialised CardFilterOptionsRecord
     */
    public CardFilterOptionsRecord(Long id, String category, String label, String value) {
        super(CardFilterOptions.CARD_FILTER_OPTIONS);

        setId(id);
        setCategory(category);
        setLabel(label);
        setValue(value);
        resetTouchedOnNotNull();
    }
}
