/*
 * This file is generated by jOOQ.
 */
package pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.SetCards;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SetCardsRecord extends UpdatableRecordImpl<SetCardsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.set_cards.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.set_cards.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.set_cards.attribute</code>.
     */
    public void setAttribute(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.set_cards.attribute</code>.
     */
    public String getAttribute() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.set_cards.card_color</code>.
     */
    public void setCardColor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.set_cards.card_color</code>.
     */
    public String getCardColor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.set_cards.card_cost</code>.
     */
    public void setCardCost(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.set_cards.card_cost</code>.
     */
    public String getCardCost() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.set_cards.card_image</code>.
     */
    public void setCardImage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.set_cards.card_image</code>.
     */
    public String getCardImage() {
        return (String) get(4);
    }

    /**
     * Create a detached, initialised SetCardsRecord
     */
    public SetCardsRecord(Long id, String attribute, String cardColor, String cardCost, String cardImage, String cardId, String cardName, String cardPower, String cardSetId, String cardText, String cardType, Integer counterAmount, Double inventoryPrice, LocalDateTime lastSyncedAt, String life, Double marketPrice, String rarity, String setId, String setName, String subTypes, String cardPrefix, String flatRarity, Object cardSemanticSearchVector, String variantIndex, String displayName, String sourceProduct) {
        super(SetCards.SET_CARDS);

        setId(id);
        setAttribute(attribute);
        setCardColor(cardColor);
        setCardCost(cardCost);
        setCardImage(cardImage);
        setCardId(cardId);
        setCardName(cardName);
        setCardPower(cardPower);
        setCardSetId(cardSetId);
        setCardText(cardText);
        setCardType(cardType);
        setCounterAmount(counterAmount);
        setInventoryPrice(inventoryPrice);
        setLastSyncedAt(lastSyncedAt);
        setLife(life);
        setMarketPrice(marketPrice);
        setRarity(rarity);
        setSetId(setId);
        setSetName(setName);
        setSubTypes(subTypes);
        setCardPrefix(cardPrefix);
        setFlatRarity(flatRarity);
        setCardSemanticSearchVector(cardSemanticSearchVector);
        setVariantIndex(variantIndex);
        setDisplayName(displayName);
        setSourceProduct(sourceProduct);
        resetTouchedOnNotNull();
    }

    /**
     * Getter for <code>public.set_cards.card_id</code>.
     */
    public String getCardId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.set_cards.card_name</code>.
     */
    public void setCardName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.set_cards.card_name</code>.
     */
    public String getCardName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.set_cards.card_power</code>.
     */
    public void setCardPower(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.set_cards.card_power</code>.
     */
    public String getCardPower() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.set_cards.card_set_id</code>.
     */
    public void setCardSetId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.set_cards.card_set_id</code>.
     */
    public String getCardSetId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.set_cards.card_text</code>.
     */
    public void setCardText(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.set_cards.card_text</code>.
     */
    public String getCardText() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.set_cards.card_type</code>.
     */
    public void setCardType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.set_cards.card_type</code>.
     */
    public String getCardType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.set_cards.counter_amount</code>.
     */
    public void setCounterAmount(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.set_cards.counter_amount</code>.
     */
    public Integer getCounterAmount() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.set_cards.card_id</code>.
     */
    public void setCardId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.set_cards.inventory_price</code>.
     */
    public Double getInventoryPrice() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>public.set_cards.inventory_price</code>.
     */
    public void setInventoryPrice(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.set_cards.last_synced_at</code>.
     */
    public LocalDateTime getLastSyncedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.set_cards.last_synced_at</code>.
     */
    public void setLastSyncedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.set_cards.life</code>.
     */
    public String getLife() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.set_cards.life</code>.
     */
    public void setLife(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.set_cards.market_price</code>.
     */
    public Double getMarketPrice() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>public.set_cards.market_price</code>.
     */
    public void setMarketPrice(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.set_cards.rarity</code>.
     */
    public String getRarity() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.set_cards.rarity</code>.
     */
    public void setRarity(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.set_cards.set_id</code>.
     */
    public String getSetId() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.set_cards.set_id</code>.
     */
    public void setSetId(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.set_cards.set_name</code>.
     */
    public String getSetName() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.set_cards.set_name</code>.
     */
    public void setSetName(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.set_cards.sub_types</code>.
     */
    public String getSubTypes() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.set_cards.sub_types</code>.
     */
    public void setSubTypes(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.set_cards.card_prefix</code>.
     */
    public String getCardPrefix() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.set_cards.card_prefix</code>.
     */
    public void setCardPrefix(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.set_cards.flat_rarity</code>.
     */
    public String getFlatRarity() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.set_cards.flat_rarity</code>.
     */
    public void setFlatRarity(String value) {
        set(21, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getCardSemanticSearchVector() {
        return get(22);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setCardSemanticSearchVector(Object value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.set_cards.variant_index</code>.
     */
    public String getVariantIndex() {
        return (String) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SetCardsRecord
     */
    public SetCardsRecord() {
        super(SetCards.SET_CARDS);
    }

    /**
     * Setter for <code>public.set_cards.variant_index</code>.
     */
    public void setVariantIndex(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.set_cards.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(24);
    }

    /**
     * Setter for <code>public.set_cards.display_name</code>.
     */
    public void setDisplayName(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.set_cards.source_product</code>.
     */
    public String getSourceProduct() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.set_cards.source_product</code>.
     */
    public void setSourceProduct(String value) {
        set(25, value);
    }
}
