/*
 * This file is generated by jOOQ.
 */
package pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pl.janda.onepiecetcg.infrastructure.persistence.jooq.Keys;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.Public;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.records.CardFilterOptionsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CardFilterOptions extends TableImpl<CardFilterOptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.card_filter_options</code>
     */
    public static final CardFilterOptions CARD_FILTER_OPTIONS = new CardFilterOptions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CardFilterOptionsRecord> getRecordType() {
        return CardFilterOptionsRecord.class;
    }

    /**
     * The column <code>public.card_filter_options.id</code>.
     */
    public final TableField<CardFilterOptionsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>public.card_filter_options.category</code>.
     */
    public final TableField<CardFilterOptionsRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.card_filter_options.label</code>.
     */
    public final TableField<CardFilterOptionsRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.card_filter_options.value</code>.
     */
    public final TableField<CardFilterOptionsRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private CardFilterOptions(Name alias, Table<CardFilterOptionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CardFilterOptions(Name alias, Table<CardFilterOptionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.card_filter_options</code> table reference
     */
    public CardFilterOptions(String alias) {
        this(DSL.name(alias), CARD_FILTER_OPTIONS);
    }

    /**
     * Create an aliased <code>public.card_filter_options</code> table reference
     */
    public CardFilterOptions(Name alias) {
        this(alias, CARD_FILTER_OPTIONS);
    }

    /**
     * Create a <code>public.card_filter_options</code> table reference
     */
    public CardFilterOptions() {
        this(DSL.name("card_filter_options"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CardFilterOptionsRecord, Long> getIdentity() {
        return (Identity<CardFilterOptionsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CardFilterOptionsRecord> getPrimaryKey() {
        return Keys.CARD_FILTER_OPTIONS_PKEY;
    }

    @Override
    public CardFilterOptions as(String alias) {
        return new CardFilterOptions(DSL.name(alias), this);
    }

    @Override
    public CardFilterOptions as(Name alias) {
        return new CardFilterOptions(alias, this);
    }

    @Override
    public CardFilterOptions as(Table<?> alias) {
        return new CardFilterOptions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CardFilterOptions rename(String name) {
        return new CardFilterOptions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CardFilterOptions rename(Name name) {
        return new CardFilterOptions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CardFilterOptions rename(Table<?> name) {
        return new CardFilterOptions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardFilterOptions where(Condition condition) {
        return new CardFilterOptions(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardFilterOptions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardFilterOptions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardFilterOptions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardFilterOptions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardFilterOptions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardFilterOptions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardFilterOptions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardFilterOptions whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardFilterOptions whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
