/*
 * This file is generated by jOOQ.
 */
package pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pl.janda.onepiecetcg.infrastructure.persistence.jooq.Keys;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.Public;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.records.CardSetsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CardSets extends TableImpl<CardSetsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.card_sets</code>
     */
    public static final CardSets CARD_SETS = new CardSets();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CardSetsRecord> getRecordType() {
        return CardSetsRecord.class;
    }

    /**
     * The column <code>public.card_sets.set_id</code>.
     */
    public final TableField<CardSetsRecord, String> SET_ID = createField(DSL.name("set_id"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.card_sets.last_synced_at</code>.
     */
    public final TableField<CardSetsRecord, LocalDateTime> LAST_SYNCED_AT = createField(DSL.name("last_synced_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.card_sets.set_name</code>.
     */
    public final TableField<CardSetsRecord, String> SET_NAME = createField(DSL.name("set_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private CardSets(Name alias, Table<CardSetsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CardSets(Name alias, Table<CardSetsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.card_sets</code> table reference
     */
    public CardSets(String alias) {
        this(DSL.name(alias), CARD_SETS);
    }

    /**
     * Create an aliased <code>public.card_sets</code> table reference
     */
    public CardSets(Name alias) {
        this(alias, CARD_SETS);
    }

    /**
     * Create a <code>public.card_sets</code> table reference
     */
    public CardSets() {
        this(DSL.name("card_sets"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CardSetsRecord> getPrimaryKey() {
        return Keys.CARD_SETS_PKEY;
    }

    @Override
    public CardSets as(String alias) {
        return new CardSets(DSL.name(alias), this);
    }

    @Override
    public CardSets as(Name alias) {
        return new CardSets(alias, this);
    }

    @Override
    public CardSets as(Table<?> alias) {
        return new CardSets(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CardSets rename(String name) {
        return new CardSets(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CardSets rename(Name name) {
        return new CardSets(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CardSets rename(Table<?> name) {
        return new CardSets(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardSets where(Condition condition) {
        return new CardSets(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardSets where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardSets where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardSets where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardSets where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardSets where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardSets where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CardSets where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardSets whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CardSets whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
