/*
 * This file is generated by jOOQ.
 */
package pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables;


import org.jooq.*;
import org.jooq.impl.*;
import org.jooq.impl.Internal;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.Indexes;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.Keys;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.Public;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.records.SetCardsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SetCards extends TableImpl<SetCardsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.set_cards</code>
     */
    public static final SetCards SET_CARDS = new SetCards();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SetCardsRecord> getRecordType() {
        return SetCardsRecord.class;
    }

    /**
     * The column <code>public.set_cards.id</code>.
     */
    public final TableField<SetCardsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>public.set_cards.attribute</code>.
     */
    public final TableField<SetCardsRecord, String> ATTRIBUTE = createField(DSL.name("attribute"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.card_color</code>.
     */
    public final TableField<SetCardsRecord, String> CARD_COLOR = createField(DSL.name("card_color"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.card_cost</code>.
     */
    public final TableField<SetCardsRecord, String> CARD_COST = createField(DSL.name("card_cost"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.card_image</code>.
     */
    public final TableField<SetCardsRecord, String> CARD_IMAGE = createField(DSL.name("card_image"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.card_image_id</code>.
     */
    public final TableField<SetCardsRecord, String> CARD_IMAGE_ID = createField(DSL.name("card_image_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.card_name</code>.
     */
    public final TableField<SetCardsRecord, String> CARD_NAME = createField(DSL.name("card_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.card_power</code>.
     */
    public final TableField<SetCardsRecord, String> CARD_POWER = createField(DSL.name("card_power"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.card_set_id</code>.
     */
    public final TableField<SetCardsRecord, String> CARD_SET_ID = createField(DSL.name("card_set_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.card_text</code>.
     */
    public final TableField<SetCardsRecord, String> CARD_TEXT = createField(DSL.name("card_text"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.set_cards.card_type</code>.
     */
    public final TableField<SetCardsRecord, String> CARD_TYPE = createField(DSL.name("card_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.counter_amount</code>.
     */
    public final TableField<SetCardsRecord, Integer> COUNTER_AMOUNT = createField(DSL.name("counter_amount"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.set_cards.inventory_price</code>.
     */
    public final TableField<SetCardsRecord, Double> INVENTORY_PRICE = createField(DSL.name("inventory_price"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.set_cards.last_synced_at</code>.
     */
    public final TableField<SetCardsRecord, LocalDateTime> LAST_SYNCED_AT = createField(DSL.name("last_synced_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.set_cards.life</code>.
     */
    public final TableField<SetCardsRecord, String> LIFE = createField(DSL.name("life"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.market_price</code>.
     */
    public final TableField<SetCardsRecord, Double> MARKET_PRICE = createField(DSL.name("market_price"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.set_cards.rarity</code>.
     */
    public final TableField<SetCardsRecord, String> RARITY = createField(DSL.name("rarity"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.set_id</code>.
     */
    public final TableField<SetCardsRecord, String> SET_ID = createField(DSL.name("set_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.set_name</code>.
     */
    public final TableField<SetCardsRecord, String> SET_NAME = createField(DSL.name("set_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.sub_types</code>.
     */
    public final TableField<SetCardsRecord, String> SUB_TYPES = createField(DSL.name("sub_types"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.card_prefix</code>.
     */
    public final TableField<SetCardsRecord, String> CARD_PREFIX = createField(DSL.name("card_prefix"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.set_cards.flat_rarity</code>.
     */
    public final TableField<SetCardsRecord, String> FLAT_RARITY = createField(DSL.name("flat_rarity"), SQLDataType.VARCHAR(255), this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<SetCardsRecord, Object> CARD_SEMANTIC_SEARCH_VECTOR = createField(DSL.name("card_semantic_search_vector"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"tsvector\""), this, "");

    /**
     * The column <code>public.set_cards.variant_index</code>.
     */
    public final TableField<SetCardsRecord, String> VARIANT_INDEX = createField(DSL.name("variant_index"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'0'::character varying"), SQLDataType.VARCHAR)), this, "");

    private SetCards(Name alias, Table<SetCardsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SetCards(Name alias, Table<SetCardsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.set_cards</code> table reference
     */
    public SetCards(String alias) {
        this(DSL.name(alias), SET_CARDS);
    }

    /**
     * Create an aliased <code>public.set_cards</code> table reference
     */
    public SetCards(Name alias) {
        this(alias, SET_CARDS);
    }

    /**
     * Create a <code>public.set_cards</code> table reference
     */
    public SetCards() {
        this(DSL.name("set_cards"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SET_CARDS_CARD_SEMANTIC_SEARCH_VECTOR);
    }

    @Override
    public Identity<SetCardsRecord, Long> getIdentity() {
        return (Identity<SetCardsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SetCardsRecord> getPrimaryKey() {
        return Keys.SET_CARDS_PKEY;
    }

    @Override
    public SetCards as(String alias) {
        return new SetCards(DSL.name(alias), this);
    }

    @Override
    public SetCards as(Name alias) {
        return new SetCards(alias, this);
    }

    @Override
    public SetCards as(Table<?> alias) {
        return new SetCards(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SetCards rename(String name) {
        return new SetCards(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SetCards rename(Name name) {
        return new SetCards(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SetCards rename(Table<?> name) {
        return new SetCards(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SetCards where(Condition condition) {
        return new SetCards(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SetCards where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SetCards where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SetCards where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SetCards where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SetCards where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SetCards where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SetCards where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SetCards whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SetCards whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
