/*
 * This file is generated by jOOQ.
 */
package pl.janda.onepiecetcg.infrastructure.persistence.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.SetCards;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_SET_CARDS_CARD_SEMANTIC_SEARCH_VECTOR = Internal.createIndex(DSL.name("idx_set_cards_card_semantic_search_vector"), SetCards.SET_CARDS, new OrderField[] { SetCards.SET_CARDS.CARD_SEMANTIC_SEARCH_VECTOR }, false);
}
