/*
 * This file is generated by jOOQ.
 */
package pl.janda.onepiecetcg.infrastructure.persistence.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.CardFilterOptions;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.CardSets;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.SetCards;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.records.CardFilterOptionsRecord;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.records.CardSetsRecord;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.records.SetCardsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CardFilterOptionsRecord> CARD_FILTER_OPTIONS_PKEY = Internal.createUniqueKey(CardFilterOptions.CARD_FILTER_OPTIONS, DSL.name("card_filter_options_pkey"), new TableField[] { CardFilterOptions.CARD_FILTER_OPTIONS.ID }, true);
    public static final UniqueKey<CardSetsRecord> CARD_SETS_PKEY = Internal.createUniqueKey(CardSets.CARD_SETS, DSL.name("card_sets_pkey"), new TableField[] { CardSets.CARD_SETS.SET_ID }, true);
    public static final UniqueKey<SetCardsRecord> SET_CARDS_PKEY = Internal.createUniqueKey(SetCards.SET_CARDS, DSL.name("set_cards_pkey"), new TableField[] { SetCards.SET_CARDS.ID }, true);
}
