/*
 * This file is generated by jOOQ.
 */
package pl.janda.onepiecetcg.infrastructure.persistence.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;

import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.CardFilterOptions;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.CardSets;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.SetCards;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.card_filter_options</code>.
     */
    public final CardFilterOptions CARD_FILTER_OPTIONS = CardFilterOptions.CARD_FILTER_OPTIONS;

    /**
     * The table <code>public.card_sets</code>.
     */
    public final CardSets CARD_SETS = CardSets.CARD_SETS;

    /**
     * The table <code>public.set_cards</code>.
     */
    public final SetCards SET_CARDS = SetCards.SET_CARDS;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CardFilterOptions.CARD_FILTER_OPTIONS,
            CardSets.CARD_SETS,
            SetCards.SET_CARDS
        );
    }
}
