/*
 * This file is generated by jOOQ.
 */
package pl.janda.onepiecetcg.infrastructure.persistence.jooq;


import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.CardFilterOptions;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.CardSets;
import pl.janda.onepiecetcg.infrastructure.persistence.jooq.tables.SetCards;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.card_filter_options</code>.
     */
    public static final CardFilterOptions CARD_FILTER_OPTIONS = CardFilterOptions.CARD_FILTER_OPTIONS;

    /**
     * The table <code>public.card_sets</code>.
     */
    public static final CardSets CARD_SETS = CardSets.CARD_SETS;

    /**
     * The table <code>public.set_cards</code>.
     */
    public static final SetCards SET_CARDS = SetCards.SET_CARDS;
}
